"""add about me table

Revision ID: 9817ca916f29
Revises: 1637c0507516
Create Date: 2025-04-10 13:48:50.660899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9817ca916f29'
down_revision = '1637c0507516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_me',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('title', sa.String(length=200), nullable=False),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('profile_image', sa.String(
                        length=500), nullable=True),
                    sa.Column('resume_url', sa.String(
                        length=500), nullable=True),
                    sa.Column('skills', sa.ARRAY(
                        sa.String(length=50)), nullable=True),
                    sa.Column('interests', sa.ARRAY(
                        sa.String(length=100)), nullable=True),
                    sa.Column('location', sa.String(
                        length=200), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('contacts', sa.Column('msg', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'msg')
    op.drop_table('about_me')
    # ### end Alembic commands ###
